# Generated by Django 6.0.2 on 2026-03-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_availability_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('supplements', 'Supplements'), ('equipment', 'Gym Equipment'), ('accessories', 'Accessories'), ('clothing', 'Gym Clothing')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
