# Generated by Django 6.0.2 on 2026-03-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_product_stock_remove_product_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('weights', 'Weights'), ('cardio', 'Cardio'), ('accessories', 'Accessories'), ('supplements', 'Supplements')], max_length=50),
        ),
    ]
