# Generated by Django 6.0.2 on 2026-03-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('weights', 'Weights'), ('cardio', 'Cardio'), ('accessories', 'Accessories')], max_length=50),
        ),
    ]
