# Generated by Django 6.0.2 on 2026-03-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_refund_rejection_reason_notifyme'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='admin_warning_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='admin_warning_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('admin_warning', 'Admin Warning - Action Required')], default='pending', max_length=20),
        ),
    ]
