# Generated by Django 6.0.2 on 2026-03-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_refund_admin_warning_date_refund_admin_warning_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='admin_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='refund_proofs/'),
        ),
        migrations.AddField(
            model_name='refund',
            name='proof_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='return',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('admin_warning', 'Admin Warning - Action Required'), ('credited', 'Credited to Customer'), ('debited', 'Debited from Seller')], default='pending', max_length=20),
        ),
    ]
